apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: kiki-cluster
spec:
  hosts:
    # --- The Masters ---
    - role: controller
      ssh:
        address: 192.168.178.175
        user: kiki
        keyPath: /Users/christopheattias/.ssh/id_ed25519
    - role: controller
      ssh:
        address: 192.168.178.199
        user: kiki
        keyPath: /Users/christopheattias/.ssh/id_ed25519
    - role: controller
      ssh:
        address: 192.168.178.196
        user: kiki
        keyPath: /Users/christopheattias/.ssh/id_ed25519

    # --- The Workers ---
    - role: worker
      ssh:
        address: 192.168.178.72
        user: kiki
        keyPath: /Users/christopheattias/.ssh/id_ed25519
    - role: worker
      ssh:
        address: 192.168.178.223
        user: kiki
        keyPath: /Users/christopheattias/.ssh/id_ed25519
    - role: worker
      ssh:
        address: 192.168.178.15
        user: kiki
        keyPath: /Users/christopheattias/.ssh/id_ed25519
    - role: worker
      ssh:
        address: 192.168.178.149
        user: kiki
        keyPath: /Users/christopheattias/.ssh/id_ed25519
    - role: worker
      ssh:
        address: 192.168.178.204
        user: kiki
        keyPath: /Users/christopheattias/.ssh/id_ed25519

  k0s:
    version: v1.35.2+k0s.0
    config:
      spec:
        network:
          # controlPlaneLoadBalancing:
          #   enabled: true
          #   type: Keepalived
          #   keepalived:
          #     vrrpInstances:
          #     - virtualIPs: ["192.168.178.0/24"]
          nodeLocalLoadBalancing:
            enabled: true
            type: EnvoyProxy
        api:
          sans:
            - 192.168.178.175
            - 192.168.178.199
            - 192.168.178.196
