apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-router
  namespace: home
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`attias.io`) || Host(`home.attias.io`)
      kind: Rule
      services:
        - name: homepage
          port: 80
      priority: 10
    #   middlewares:
    #     - name: authentik
    #       namespace: traefik
    # - kind: Rule
    #   match: "(Host(`attias.io`) && PathPrefix(`/outpost.goauthentik.io/`)) || (Host(`home.attias.io`) && PathPrefix(`/outpost.goauthentik.io/`))"
    #   priority: 15
    #   services:
    #       - kind: Service
    #         name: ak-outpost-authentik-embedded-outpost
    #         namespace: authentik
    #         port: 9000
  tls:
    certResolver: le