[all:vars]
ansible_python_interpreter=auto_silent

[all_nodes:children]
pihole

[pihole]
pihole-80 ansible_host=192.168.178.77 proxmox_vmid=109 ansible_connection=community.proxmox.proxmox_pct_remote ansible_user=root
pihole-238 ansible_host=192.168.178.220 proxmox_vmid=107 ansible_connection=community.proxmox.proxmox_pct_remote ansible_user=root
