apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-proxmox
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    namespace: csi-proxmox
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: proxmox-csi-plugin
    repoURL: oci://ghcr.io/sergelogvinov/charts/proxmox-csi-plugin
    targetRevision: 0.5.5
    helm:
      releaseName: proxmox-csi-plugin
      valuesObject:
        node:
          kubeletDir: /var/lib/k0s/kubelet
        config:
          clusters:
            - url: https://192.168.178.69:8006/api2/json
              insecure: true
              token_id: "kubernetes-csi@pve!csi"
              token_secret: "key"
              region: p700

        # Deploy CSI controller only on control-plane nodes
        nodeSelector:
          node-role.kubernetes.io/control-plane: ""
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            effect: NoSchedule
