apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
      enabled: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
  destination:
    namespace: vaultwarden
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://guerzon.github.io/vaultwarden
    targetRevision: 0.36.0
    chart: vaultwarden
    helm:
      valuesObject:
        image:
          repository: vaultwarden/server
          tag: 1.35.7
        domain: "https://vault.attias.io"
        database:
          type: postgresql
          existingSecret: "vaultwarden-db-app"
          existingSecretKey: "uri"
        adminToken:
          existingSecret: "vault-admin-token"
          existingSecretKey: "admin-token"
