apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data-pvc
  namespace: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-ceph
  resources:
    requests:
      storage: 10Gi