apiVersion: v1
kind: Service
metadata:
  name: nas-cronmaster
  namespace: nas
spec:
  type: ExternalName
  externalName: 192.168.178.33
  ports:
    - protocol: TCP
      port: 40123
      targetPort: 40123
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nas-cronmaster-router
  namespace: nas
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`cron.nas.attias.io`)
      kind: Rule
      services:
        - name: nas-cronmaster
          port: 40123
      priority: 10
    #   middlewares:
    #     - name: authentik
    #       namespace: traefik
    # - kind: Rule
    #   match: "Host(`backrest.attias.io`) && PathPrefix(`/outpost.goauthentik.io/`)"
    #   priority: 15
    #   services:
    #       - kind: Service
    #         name: ak-outpost-authentik-embedded-outpost
    #         namespace: authentik
    #         port: 9000
  tls:
    certResolver: le