apiVersion: v1
kind: Service
metadata:
  name: nas-webdav
  namespace: nas
spec:
  type: ExternalName
  externalName: 192.168.178.219
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nas-webdav-router
  namespace: nas
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`webdav.nas.attias.io`)
      kind: Rule
      services:
        - name: nas-webdav
          port: 5005
      priority: 10
  tls:
    certResolver: le