[all:vars]
ansible_user=kiki
ansible_python_interpreter=auto_silent

[all_nodes:children]
masters
workers
lxc

[masters]
master-01 ansible_host=192.168.178.175
master-02 ansible_host=192.168.178.199
master-03 ansible_host=192.168.178.196

[workers]
worker-01 ansible_host=192.168.178.72
worker-02 ansible_host=192.168.178.223
worker-03 ansible_host=192.168.178.15
worker-04 ansible_host=192.168.178.149
worker-05 ansible_host=192.168.178.204

[lxc]
pihole-80 ansible_host=192.168.178.77 proxmox_vmid=109 ansible_connection=community.proxmox.proxmox_pct_remote ansible_user=root
peanut-lxc ansible_host=192.168.178.77 proxmox_vmid=108 ansible_connection=community.proxmox.proxmox_pct_remote ansible_user=root
plex-lxc ansible_host=192.168.178.69 proxmox_vmid=105 ansible_connection=community.proxmox.proxmox_pct_remote ansible_user=root
pihole-238 ansible_host=192.168.178.220 proxmox_vmid=107 ansible_connection=community.proxmox.proxmox_pct_remote ansible_user=root
pbs-lxc ansible_host=192.168.178.220 proxmox_vmid=110 ansible_connection=community.proxmox.proxmox_pct_remote ansible_user=root
