
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-pushgateway
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: prometheus-pushgateway
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 3.6.0
    helm:
      releaseName: prometheus-pushgateway
      valuesObject:
        serviceMonitor:
          enabled: true
          namespace: monitoring
          additionalLabels:
            release: kube-prometheus-stack

