apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.15.3
    helm:
      releaseName: metallb
      valuesObject:
        prometheus:
          namespace: monitoring
          serviceAccount: "kube-prometheus-stack-prometheus"
          podMonitor:
            # enable support for Prometheus Operator
            enabled: false
            additionalLabels:
              release: kube-prometheus-stack
          serviceMonitor:
            # enable support for Prometheus Operator
            enabled: true
            speaker:
              # optional additional labels for the speaker serviceMonitor
            additionalLabels:
              release: kube-prometheus-stack

            controller:
              # optional additional labels for the controller serviceMonitor
            additionalLabels:
              release: kube-prometheus-stack
          prometheusRule:
            # enable alertmanager alerts
            enabled: true
            additionalLabels:
              release: kube-prometheus-stack
