apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    namespace: pihole
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: pihole
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    targetRevision: 2.35.0
    helm:
      releaseName: pihole
      valuesObject:
        image:
          repository: pihole/pihole
          tag: 2025.11.1
          pullPolicy: IfNotPresent

        DNS1: "192.168.178.80#5335"
        DNS2: ""

        dnsmasq:
          enableCustomDnsMasq: true
          customDnsEntries:
          # --- Specific Overrides (External VPS) ---
          - address=/kikiflix.eu/91.98.236.199
          - address=/tailscale.attias.io/photos.attias.io/91.98.236.199
          - address=/kiki.vps/vps.kiki.home/100.64.0.2

          # --- Nested Wildcard for MiniPC Nodes (*.node.attias.io) ---
          - address=/node.attias.io/192.168.178.103

          # --- General Wildcard for Main Traefik LB (*.attias.io) ---
          - address=/hc.attias.io/authentik.attias.io/attias.io/192.168.178.200

          # --- Other Static Local Entries ---
          - address=/pihole.pve.kiki.home/192.168.178.80
          - address=/pihole.kiki.home/192.168.178.203
          - address=/kiki.node/node.kiki.home/192.168.178.34
          - address=/nas.kiki.home/192.168.178.33
          - address=/offsite.kiki.home/100.64.0.6
          - address=/k0s-master-01/192.168.178.175
          - address=/k0s-master-02/192.168.178.199
          - address=/k0s-master-03/192.168.178.196
          - address=/k0s-worker-01/192.168.178.72
          - address=/k0s-worker-02/192.168.178.223
          - address=/k0s-worker-03/192.168.178.15

        persistentVolumeClaim:
          enabled: true
          storageClass: proxmox-ceph
          size: 5Gi

        admin:
          existingSecret: "pihole-secret"

        # kubernetes services for web admin
        serviceWeb:
          loadBalancerIP: 192.168.178.203
          annotations:
            metallb.universe.tf/allow-shared-ip: pihole-svc
          type: LoadBalancer
        
        # create a kubernetes service and expose
        # port 53 outside of cluster on the local network
        serviceDns:
          mixedService: true
          loadBalancerIP: 192.168.178.203
          annotations:
            metallb.universe.tf/allow-shared-ip: pihole-svc
          type: LoadBalancer

        extraVolumes: 
          - name: shm-volume
            emptyDir:
              medium: Memory
              sizeLimit: 256Mi
        extraVolumeMounts:
          - name: shm-volume
            mountPath: /dev/shm
