apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: authentik-backup-store
  namespace: authentik
spec:
  retentionPolicy: "7d"
  configuration:
    destinationPath: s3://backup-authentik
    endpointURL: http://192.168.178.69:7480
    s3Credentials:
      accessKeyId:
        name: barman-secret
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: barman-secret
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip