apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
      enabled: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
  destination:
    namespace: authentik
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.goauthentik.io/
    targetRevision: 2026.2.2
    chart: authentik
    helm:
      valuesObject:
        authentik:
          # -- whether to create the authentik configuration secret
          enabled: true
          # -- Log level for server and worker
          log_level: info
          # -- Secret key used for cookie singing and unique user IDs,
          # don't change this after the first install
          secret_key: file:///authentik-secret/secret_key 
          email:
            # -- SMTP Server emails are sent from, fully optional
            host: "smtp-relay.brevo.com"
            # -- SMTP server port
            port: 587
            # -- SMTP credentials, when left empty, no authentication will be done
            username: file:///authentik-secret/smtp_username 
            # -- SMTP credentials, when left empty, no authentication will be done
            password: file:///authentik-secret/smtp_password
            # -- Use StartTLS. Enable either use_tls or use_ssl, they can't be enabled at the same time.
            use_tls: true
            # -- Use SSL. Enable either use_tls or use_ssl, they can't be enabled at the same time.
            use_ssl: false
            # -- Connection timeout
            timeout: 30
            # -- Email from address, can either be in the format "foo@bar.baz" or "authentik <foo@bar.baz>"
            from: "Authentikiki <authentik@attias.io>"
          postgresql:
            # -- set the postgresql hostname to talk to
            # if unset and .Values.postgresql.enabled == true, will generate the default
            # @default -- `{{ .Release.Name }}-postgresql`
            host: file:///postgres-creds/host
            # -- postgresql Database name
            # @default -- `authentik`
            name: file:///postgres-creds/dbname
            # -- postgresql Username
            # @default -- `authentik`
            user: file:///postgres-creds/user
            password: file:///postgres-creds/password
            port: 5432

        server:
          metrics:
            # -- deploy metrics service
            enabled: true
            serviceMonitor:
              # -- enable a prometheus ServiceMonitor
              enabled: true
          volumes:
            - name: postgres-creds
              secret:
                secretName: authentik-db-app
            - name: authentik-secret
              secret:
                secretName: authentik-secret
          volumeMounts:
            - name: postgres-creds
              mountPath: /postgres-creds
              readOnly: true
            - name: authentik-secret
              mountPath: /authentik-secret
              readOnly: true

        worker:
          metrics:
            # -- deploy metrics service
            enabled: true
            serviceMonitor:
              # -- enable a prometheus ServiceMonitor
              enabled: true
          volumes:
            - name: postgres-creds
              secret:
                secretName: authentik-db-app
            - name: authentik-secret
              secret:
                secretName: authentik-secret
          volumeMounts:
            - name: postgres-creds
              mountPath: /postgres-creds
              readOnly: true
            - name: authentik-secret
              mountPath: /authentik-secret
              readOnly: true

        prometheus:
          rules:
            enabled: true
            namespace: monitoring
            labels: 
              release: kube-prometheus-stack
