apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: immich-nfs-backup
  namespace: photos
spec:
  backup:
    schedule: "0 3 * * *" # Runs daily at 3:00 AM
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
    concurrentRunsAllowed: false
    labelSelectors:
      - matchLabels:
        - backup: "true"
    backend:
      repoPasswordSecretRef:
        name: backup-repo-secret
        key: password
      local:
        mountPath: "/mnt/backup-repository"
      volumeMounts:
        - name: nas-repo
          mountPath: "/mnt/backup-repository"
          subPath: immich_restic
    volumes:
      - name: nas-repo
        persistentVolumeClaim:
          claimName: immich-backup-pvc
  prune:
    schedule: "0 4 * * 0" # Every Sunday at 4:00 AM
    retention:
      keepDaily: 7
      keepWeekly: 4
      keepMonthly: 6
