apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
  namespace: photos
  labels:
    backup: "true"
    k8up.io/backup-restic-args: '["--exclude", "/data/immich-library-pvc/lost+found"]'
spec:
  accessModes:
    - ReadWriteOnce
  # Immich uses the volume as a standard filesystem for image/video storage
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Ti
  storageClassName: proxmox-ceph
