apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    namespace: photos
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: oci://ghcr.io/immich-app/immich-charts/immich
    targetRevision: 0.11.1
    chart: immich
    helm:
      valuesObject:
        controllers:
          main:
            containers:
              main:
                image:
                  repository: ghcr.io/immich-app/immich-server
                  tag: v2.7.4
                env:
                  - name: REDIS_HOSTNAME
                    value: immich-redis
                  - name: DB_URL
                    valueFrom:
                      secretKeyRef:
                        name: immich-db-app
                        key: uri
        immich:
          metrics:
            enabled: false
          persistence:
            library:
              existingClaim: immich-library-pvc
          configuration:
            trash:
              enabled: true
              days: 30
            storageTemplate:
              enabled: true
              template: '{{ "{{" }}y{{ "}}" }}/{{ "{{" }}y{{ "}}" }}-{{ "{{" }}MM{{ "}}" }}-{{ "{{" }}dd{{ "}}" }}/{{ "{{" }}filename{{ "}}" }}'
        persistence:
          cache:
            enabled: true
            size: 10Gi
            type: emptyDir
            accessMode: ReadWriteMany
            storageClass: proxmox-ceph
        server:
          enabled: true
          service:
            main:
              type: LoadBalancer
              targetPort: 2283
        machine-learning:
          enabled: true