# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: homeassistant-config-pvc
#   namespace: home
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: proxmox-ceph
#   resources:
#     requests:
#       storage: 1Gi