# --- Specific Overrides (External VPS) ---
address=/kikiflix.eu/91.98.236.199
address=/tailscale.attias.io/photos.attias.io/91.98.236.199
address=/kiki.vps/vps.kiki.home/100.64.0.2

# --- Nested Wildcard for MiniPC Nodes (*.node.attias.io) ---
# address=/node.attias.io/192.168.178.103

# --- General Wildcard for Main Traefik LB (*.attias.io) ---
address=/hc.attias.io/authentik.attias.io/attias.io/192.168.178.200

# --- Other Static Local Entries ---
address=/pihole.pve.kiki.home/192.168.178.80
address=/pihole.pvemaster.kiki.home/192.168.178.238
address=/kiki.node/node.kiki.home/192.168.178.34
address=/nas.kiki.home/192.168.178.33
address=/offsite.kiki.home/100.64.0.6
address=/km1.kiki.home/192.168.178.175
address=/km2.kiki.home/192.168.178.199
address=/km3.kiki.home/192.168.178.196
address=/kw1.kiki.home/192.168.178.72
address=/kw2.kiki.home/192.168.178.223
address=/kw3.kiki.home/192.168.178.15
address=/kw4.kiki.home/192.168.178.149
address=/kw5.kiki.home/192.168.178.204
address=/nextcloud.kiki.home/192.168.178.158
address=/ollama.kiki.home/192.168.178.82
