[all:vars]
ansible_python_interpreter=auto_silent

[all_nodes:children]
pve_all
vms
masters
workers
lxc
pihole

[pvemaster_host]
pvemaster ansible_host=192.168.178.69 ansible_user=root

[pvelenovo_host]
pvelenovo ansible_host=192.168.178.77 ansible_user=root

[pvenode_host]
pvenode ansible_host=192.168.178.220 ansible_user=root

[pve_all:children]
pvemaster_host
pvelenovo_host
pvenode_host

[masters]
master-01 ansible_host=192.168.178.175 ansible_user=kiki
master-02 ansible_host=192.168.178.199 ansible_user=kiki
master-03 ansible_host=192.168.178.196 ansible_user=kiki

[workers]
worker-01 ansible_host=192.168.178.72 ansible_user=kiki
worker-02 ansible_host=192.168.178.223 ansible_user=kiki
worker-03 ansible_host=192.168.178.15 ansible_user=kiki
worker-04 ansible_host=192.168.178.149 ansible_user=kiki
worker-05 ansible_host=192.168.178.204 ansible_user=kiki

[vms]
ollama ansible_host=192.168.178.82 ansible_user=kiki
nextcloud ansible_host=192.168.178.158 ansible_user=kiki

[lxc]
peanut-lxc ansible_host=192.168.178.77 proxmox_vmid=108 ansible_connection=community.proxmox.proxmox_pct_remote ansible_user=root
plex-lxc ansible_host=192.168.178.69 proxmox_vmid=105 ansible_connection=community.proxmox.proxmox_pct_remote ansible_user=root
pbs-lxc ansible_host=192.168.178.220 proxmox_vmid=110 ansible_connection=community.proxmox.proxmox_pct_remote ansible_user=root

[pihole]
pihole-80 ansible_host=192.168.178.77 proxmox_vmid=109 ansible_connection=community.proxmox.proxmox_pct_remote ansible_user=root
pihole-238 ansible_host=192.168.178.220 proxmox_vmid=107 ansible_connection=community.proxmox.proxmox_pct_remote ansible_user=root
