---
- name: Update Pi-hole Custom DNS Configuration
  hosts: pihole
  tasks:
    - name: Ensure the local config file exists
      ansible.builtin.stat:
        path: "./05-custom-kiki.conf"
      delegate_to: localhost
      register: local_file

    - name: Fail if local config is missing
      ansible.builtin.fail:
        msg: "The local dnsmasq config file was not found!"
      when: not local_file.stat.exists

    - name: Push custom dnsmasq config to Pi-holes
      ansible.builtin.copy:
        src: "./05-custom-kiki.conf"
        dest: "/etc/dnsmasq.d/05-custom-kiki.conf"
        owner: root
        group: root
        mode: '0644'
      register: config_copy

    - name: Reload Pi-hole DNS and Restart FTL
      ansible.builtin.shell: |
        pihole reloaddns
        systemctl restart pihole-FTL
      when: config_copy.changed
      register: service_restart

    - name: Confirm Pi-hole status
      ansible.builtin.command: /usr/local/bin/pihole status
      register: pihole_status
      changed_when: false

    - name: Show Pi-hole Status
      ansible.builtin.debug:
        var: pihole_status.stdout_lines