apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kometa
  name: kometa
  namespace: arr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: proxmox-ceph