---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-auto-languages
  namespace: arr
  labels:
    app: plex-auto-languages
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: plex-auto-languages
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plex-auto-languages
        tier: backend
      name: plex-auto-languages
    spec:
      containers:
        - name: plex-auto-languages
          image: remirigal/plex-auto-languages:v1.2.3
          env:
            - name: TZ
              value: UTC
          volumeMounts:
            - mountPath: /config
              name: plex-auto-languages-config
            - mountPath: /config/config.yaml
              name: plex-auto-languages-yaml
              subPath: config.yaml
      volumes:
        - name: plex-auto-languages-config
          persistentVolumeClaim:
            claimName: plex-auto-languages-config
        - name: plex-auto-languages-yaml
          configMap:
            name: plex-auto-languages-yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-auto-languages-config
  namespace: arr
  labels:
    app: plex-auto-languages
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-ceph
  resources:
    requests:
      storage: 100Mi
