apiVersion: v1
kind: Service
metadata:
  name: tautulli
  namespace: arr
  labels:
    app.kubernetes.io/name: tautulli
spec:
  type: ClusterIP
  ports:
    - name: "8181"
      port: 8181
      targetPort: 8181
  selector:
    app.kubernetes.io/name: tautulli