apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
      enabled: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: oci://quay.io/jetstack/charts/cert-manager
    targetRevision: v1.20.2
    chart: cert-manager
    helm:
      valuesObject:
        crds:
          enabled: true
        prometheus:
          enabled: true
          servicemonitor:
            enabled: true